sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lc0J1jnsa1mrTN00dsWMBN7a0+MaqEmecFA7tJo0uVx0pvaI6CwVP/To7JcMFYHTG5bmOeNpaJuKXyWzqUiffdtEnmcVJM7oeTCjty5roHhf++Copy15M4BqXKSkMtHVYYAUMxxWBOKRiquxfYuWmrpyJBSODoxNt4Skw4zQ++EmT9uNpkJcEvqqDCGbjWd7Oz+NGe6nu/gT59N1tyZ2RHOVo+Rf8hYbdyJirqWREDXoFGJwUgg9ngwHE9WLEB0CKdX75ZsElvnWL51ohEaFUA9HmWp5e8jUJdfB+AbRAf7I6+B4si71OqHNU7bKd1MISHr74svdne1fohrzXTBox3ONipp88pExVC1JK2r+rFznp0arA1QoRawg+xboNx6HK3YFlo38SlyoopRV03xCc7WyVNyr+yLxo3zfkDbahBVyyHX7RXJQEF3P/KzlTyESleLIuBif4BG/sky9+yopYhLHGjQlWRFCcvFEXlBn1mYxgZYok9xZTddn7dkKl5qu7dM/nuC8SPt1hMHLUFpM14Z0PZyUSCGpRWaNItqRFDDfsdXc/3AvabZWSKXobmg3iyNrpqNzvbIBhvlEP7SDbM6cAA63W4G6Ocg8UJXHOVc/07W0BWdMUY3Cg2lWPEDyUWAJVI0y4huI8pNrz4xJg9uW+nP62SxKYHn1MdNC96E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Boss-and-the-Machine--A-Chronicle-of-the-Politicians-and-Party-Organization_3040
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy